backend:
    name: github
    repo: awesome1888/grayscale-promo-gatsbyjs-starter
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
    - name: block
      label: Block
      folder: content/blocks
      create: true
      identifier_field: id
      fields:
          - { name: id, label: ID }
          - { name: sort, label: Sort, widget: number, valueType: int }
          - { name: effect, label: Effect, widget: list, allow_add: false }
          - { name: body, label: Body, widget: markdown }
          - label: 'Featured Image'
            name: 'thumbnail'
            widget: 'image'
            media_library:
                config:
                    multiple: true
