backend:
    name: github
    repo: awesome1888/grayscale-promo-gatsbyjs-starter
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
    - name: block
      label: Block
      folder: content/blocks
      create: true
      identifier_field: id
      fields:
          - { name: id, label: ID }
          - { name: sort, label: Sort, widget: number, valueType: int }
          - { name: effect, label: Effect, widget: list, allow_add: false }
          - { name: body, label: Body, widget: markdown }
          - label: 'Graphic'
            name: 'graphic'
            widget: 'list'
            fields:
                - name: image
                  label: 'Image'
                  widget: 'image'
                  media_library:
                      config:
                      multiple: true
                - name: author
                  label: 'Author'
                  widget: string
                - name: source
                  label: 'Source'
                  widget: string
